# Inspired from commercialhaskell/stack
#
# Here, we test with both stack and cabal. The reasons to test with cabal are
# twofold:
#
# 1. We want to ensure that the bootstrapping case works
#
# 2. Building with stack would be too easy a test, since it guarantees us a
# sane build environment. In CI, we want to make our life more difficult, so we
# use cabal without any Stackage snapshots.
#
language: c
sudo: false

cache:
    directories:
        - $HOME/.ghc
        - $HOME/.cabal
        - $HOME/.stack

matrix:
  include:

    - env: BUILD=cabal CABALVER=1.24 GHCVER=8.0.2
      compiler: ": #GHC 8.0.2"
      addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.2,happy-1.19.5], sources: [hvr-ghc]}}

    - env: BUILD=stack GHCVER=8.0.2 STACK_YAML=stack.yaml
      compiler: ": #stack 8.0.2"
      addons: {apt: {packages: [cabal-install-head,ghc-8.0.2,happy-1.19.5], sources: [hvr-ghc]}}

    - env: BUILD=stack-osx STACK_YAML=stack.yaml
      compiler: ": #stack osx latest"
      os: osx

# Note: the distinction between `before_install` and `install` is not important.
# - in before_install we install build tools
# - in install we install (haskell) dependencies
before_install:
 - unset CC
 - export PATH=/opt/happy/1.19.5/bin:$PATH
 - case "$BUILD" in
     stack)
       export PATH=$HOME/.local/bin:/opt/ghc/$GHCVER/bin:$PATH;;
     stack-osx)
       export PATH=$HOME/.local/bin:$PATH;;
     cabal)
       export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH;;
   esac
 - ./.travis-setup.sh

install:
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - case "$BUILD" in
     stack)
       stack --system-ghc --compiler ghc-"$GHCVER" --no-terminal test --only-dependencies;;
     stack-osx)
       stack --no-system-ghc --no-terminal test --only-dependencies;;
     cabal)
       cabal --version;
       travis_retry cabal update;
       rm -f $(stack path --dist-dir)/stack-*.tar.gz;
       stack sdist --pvp-bounds=both;
       tar xf $(stack path --dist-dir)/stack-*.tar.gz --wildcards --strip-components=1 '*/stack.cabal';
       cabal install --only-dependencies --enable-tests --enable-benchmarks --force-reinstalls --ghc-options=-O0;;
   esac

script:
 - case "$BUILD" in
     stack)
       stack --system-ghc --compiler ghc-"$GHCVER" --no-terminal test --haddock --no-haddock-deps;;
     stack-osx)
       stack --no-system-ghc --no-terminal test --haddock --no-haddock-deps;;
     cabal)
       cabal configure --enable-tests --enable-benchmarks -v2 --ghc-options="-O0 -Werror";
       cabal build;
       cabal test;
       cabal check;
       cabal sdist;
       cabal copy;
       SRC_TGZ=$(cabal info . | awk '{print $2;exit}').tar.gz &&
       (cd dist && cabal install --force-reinstalls "$SRC_TGZ");;
   esac

deploy:

    provider: releases

    # encrypted environment variables are not available for pull requests from
    # forks.
    api_key:
        secure: TrQkoxCtTrqtXNVVV24b1rE6O8Lv1p/x1CwMx/yDoSzCCpBewk3jIr1ExJYHJ+JKXOJQAxuP/7LTJ76crchV7geco4NAycOR9Up1at+dO07eKc9gtm9YrI3+o3Es/zXSH0tN+xM7zYi52vdcFLcFtVVMl6dHaJgeKwQkNDa4/S4BimePzaRTeZ31TJ69fhoLRT30MeFFHLGF7xXRiYm6yu8AirciLfx8F2YzTA4utPpGLQT3tTRUUtsWvOghI+Sd/lJNRp9i9gY1UfbBbIk8dvIFA4fIv6T1OW1ChI4U/2OiDgdBjX9cd8rIBY0sUIHzOGe1p34VetDQrZVf6ERtssUvX2jKoK15kGWeCmaBgDHFfQ9nA/qo+y+GGcTriJtyD10QVsVNRrrVBnntuW01h3/dx3KJ51jiE7E0WyoJhae2vPz4bpjlxOJlCbQ4T18MlH0N7pm5TZwWvgfAXjK6zfhg90h8zrUGXAK1yuPelk9pIBjmIifC/7Iwz5ZcS3Vc0HerUkox84L5gqM6qtxojJyPJesquD7imNFtNTAiHG22k3xz+NrLG1bo2x03MQ1wTZg7D1Vxg7DR5Nts9JTgvxq6ttGfG4UTYAD5L6XFtUWTNRhYcqqZvS5YE68E8V+FX1bbUJMQwlH0lnHNqD9Lo3Q/EHG1I+gS8BnVpZF2q7w=
    file:
        - dist/build/stutter/stutter
    on:
        tags: true
        # Only upload the latest cabal generated executable
        condition : "\"$GHCVER\" = \"8.0.2\" && \"$BUILD\" = \"cabal\""
