resolver: lts-8.15
packages:
- '.'
- location:
    git: https://github.com/nmattia/snipcheck.git
    commit: 4e91e038de3259a23a2a32a0192baaf950da3ffd
  extra-dep: true
extra-deps: []
flags: {}
extra-package-dbs: []
