resolver: lts-8.00
packages:
- '.'
- location:
    git: https://github.com/nmattia/snipcheck.git
    commit: bebddf6e90c9e54b6ab0ab54d5d7455fc7d2e494
  extra-dep: true
extra-deps: []
flags: {}
extra-package-dbs: []
