resolver: lts-8.15
packages:
- '.'
- location:
    git: https://github.com/nmattia/snipcheck.git
    commit: 11de2819a840d2a0f2f662882eb649c9c8edf9f4
  extra-dep: true
extra-deps: []
flags: {}
extra-package-dbs: []
