version: 2

jobs:
  build-nix:
    machine:
        enabled: true
    steps:
      - run:
          name: Install Nix
          command: |
            sudo mkdir -p /nix
            sudo chown circleci /nix
            bash <(curl https://nixos.org/nix/install)
      - checkout
      - run:
          name: Nix build
          command: |
            . ~/.nix-profile/etc/profile.d/nix.sh
            nix-build --no-out-link --option sandbox true
      - run:
          name: Run tests
          command: |
            . ~/.nix-profile/etc/profile.d/nix.sh
            ./script/test

workflows:
  version: 2
  build:
    jobs:
      - build-nix
